# -*- coding: utf-8 -*-
"""markov_chain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSJAJXZpQGG8FUL7r3Xkxf8xIEWJsjJ8
"""

#Import library
import numpy as np

#Create a 5 by 5 array and fill the entries with random numbers between 0 and 1
P = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        P[i,j] = np.random.rand()

#Nomralize the rows by dividing each entry by the sum of its row
for i in range(5):
    normal = np.sum(P[i,:])
    for j in range(5):
        P[i,j] = P[i,j]/normal

#Create a probability distrubtion with random entries between 0 and 1
p = np.zeros((5,1))

#Normalize the probability distribution
for j in range(5):
    p[j] = np.random.rand()
p = p/np.sum(p)

#Covert P from an array to a matrix
P_matrix = np.matrix(P)

#Display P and probability distribution
print('The transition matrix is: \n' ,P_matrix)
print('\nThe probability distribution is: \n', p)

#Initialize variables for transition rule
x = 0
p_hat = p

#Perform 50 instances of the transition rule
while x < 50:
    p_hat = np.dot(P_matrix.T,p_hat)
    x = x + 1
print('\nThe 50th probability distribution is: \n', p_hat)

#Find the eigenvalues and vectors for the transpose of matrix P
eigenvalues, eigenvectors = np.linalg.eig(P_matrix.T)

#Find eigenvector corresponding to eigenvalue 1 and normalize
v = eigenvectors[:,0].real
v_normal = v/np.sum(v)
print('\nThe stationary distribution is: \n', v_normal)

#Take the absolute value of the difference between
#the 50th probability distirbution and the stationary distribution
difference = np.abs(p_hat - v_normal)

#Test if the difference of each element is smaller than 10^-5 and return verdict
j = 0
while j in range(5):
    if difference[j] > 10 ** -5:
        print('\nThe 50th probability distirbution and the stationary distribution do not match!')
        break
    elif difference[j] < 10 ** -5 and j == 4:
        print('\nThe 50th probability distirbution and the stationary distribution match!')
        break
    else:
        j += 1

